import './global.css';
import {CustomThemeProvider } from "./theme"

export const metadata = {
  title: 'Welcome to ugh',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body><CustomThemeProvider>{children}</CustomThemeProvider></body>
    </html>
  );
}
